// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFNpHfzMmxwc2vP0XmjsPGWQNE2Xtcdyo',
    appId: '1:1066197753009:web:1009b78841ea52ff995690',
    messagingSenderId: '1066197753009',
    projectId: 'firebas-cw4360',
    authDomain: 'firebas-cw4360.firebaseapp.com',
    storageBucket: 'firebas-cw4360.appspot.com',
    measurementId: 'G-LYN1V8PXNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7o0edFchN8vJYpUeqXYjqpwWCvzGLUcU',
    appId: '1:1066197753009:android:209f6eeee2d39d4d995690',
    messagingSenderId: '1066197753009',
    projectId: 'firebas-cw4360',
    storageBucket: 'firebas-cw4360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiGY18aO9GI32KwMVwKki5L3taGSEdOcA',
    appId: '1:1066197753009:ios:8d7d306985965b25995690',
    messagingSenderId: '1066197753009',
    projectId: 'firebas-cw4360',
    storageBucket: 'firebas-cw4360.appspot.com',
    iosBundleId: 'com.example.firebasecw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiGY18aO9GI32KwMVwKki5L3taGSEdOcA',
    appId: '1:1066197753009:ios:8d7d306985965b25995690',
    messagingSenderId: '1066197753009',
    projectId: 'firebas-cw4360',
    storageBucket: 'firebas-cw4360.appspot.com',
    iosBundleId: 'com.example.firebasecw',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFNpHfzMmxwc2vP0XmjsPGWQNE2Xtcdyo',
    appId: '1:1066197753009:web:fd0aae1b71225e0c995690',
    messagingSenderId: '1066197753009',
    projectId: 'firebas-cw4360',
    authDomain: 'firebas-cw4360.firebaseapp.com',
    storageBucket: 'firebas-cw4360.appspot.com',
    measurementId: 'G-DB2HGELYP5',
  );

}